Repository arangodb/docs, pull requests merged in 2019-10, with the labels that each got.

#179 SmartJoin to SmartJoins
  3.5/release-notes-new-features35.md
  3.5/smartjoins.md
  3.6/release-notes-new-features35.md
  3.6/smartjoins.md
Labels: 9 CLA available

#161 SmartGraphs examples not rendered correctly
  3.4/smartjoins.md
  3.5/generated/Examples/smartGraphCreate1_cluster.generated
  3.5/generated/Examples/smartGraphCreate2_cluster.generated
  3.5/generated/Examples/smartGraphCreate3_cluster.generated
  3.5/generated/Examples/smartGraphCreateGraphHowTo1_cluster.generated
  3.5/generated/Examples/smartGraphCreateGraphHowTo2_cluster.generated
  3.5/generated/Examples/smartGraphCreateGraphHowTo3_cluster.generated
  3.5/generated/Examples/smartGraphModify1_cluster.generated
  3.5/generated/Examples/smartGraphModify2_cluster.generated
  3.5/generated/Examples/smartGraphModify3_cluster.generated
  3.5/generated/Examples/smartGraphModify4_cluster.generated
  3.5/generated/Examples/smartGraphModify5_cluster.generated
  3.5/generated/Examples/smartGraphModify6_cluster.generated
  3.5/generated/Examples/smartGraphModify7_cluster.generated
  3.5/generated/Examples/smartGraphRemove1_cluster.generated
  3.5/generated/Examples/smartGraphRemove2_cluster.generated
  3.5/graphs-general-graphs-management.md
  3.5/graphs-general-graphs.md
  3.5/graphs-smart-graphs-management.md
  3.5/graphs-smart-graphs.md
  3.5/smartjoins.md
  3.6/generated/Examples/smartGraphCreate1_cluster.generated
  3.6/generated/Examples/smartGraphCreate2_cluster.generated
  3.6/generated/Examples/smartGraphCreate3_cluster.generated
  3.6/generated/Examples/smartGraphCreateGraphHowTo1_cluster.generated
  3.6/generated/Examples/smartGraphCreateGraphHowTo2_cluster.generated
  3.6/generated/Examples/smartGraphCreateGraphHowTo3_cluster.generated
  3.6/generated/Examples/smartGraphModify1_cluster.generated
  3.6/generated/Examples/smartGraphModify2_cluster.generated
  3.6/generated/Examples/smartGraphModify3_cluster.generated
  3.6/generated/Examples/smartGraphModify4_cluster.generated
  3.6/generated/Examples/smartGraphModify5_cluster.generated
  3.6/generated/Examples/smartGraphModify6_cluster.generated
  3.6/generated/Examples/smartGraphModify7_cluster.generated
  3.6/generated/Examples/smartGraphRemove1_cluster.generated
  3.6/generated/Examples/smartGraphRemove2_cluster.generated
  3.6/graphs-general-graphs-management.md
  3.6/graphs-general-graphs.md
  3.6/graphs-smart-graphs-management.md
  3.6/graphs-smart-graphs.md
  3.6/smartjoins.md
Labels: 1 Bug, 9 WIP

#184 Known issues: two shutdown issues fixed in v3.5.1
  3.5/programs-arangobackup.md
  3.5/release-notes-known-issues35.md
  3.6/programs-arangobackup.md
  3.6/release-notes-known-issues35.md
  3.6/release-notes-known-issues36.md
Labels: 1 Bug

#153 add date ranges for AQL date/time functions
  3.6/release-notes-upgrading-changes36.md
Labels: 1 Feature

#186 Missing 3.5 changelog link (add)
  3.5/release-notes.md
  3.6/release-notes.md
Labels: 1 Bug

#143 Update driver pages for 3.5 release
  3.5/deployment-kubernetes-backup-policy-resource.md
  3.5/deployment-kubernetes-backup-resource.md
  3.5/deployment-kubernetes-deployment-resource.md
  3.5/deployment-kubernetes-helm.md
  3.5/deployment-kubernetes-metrics.md
  3.5/deployment-kubernetes.md
  3.5/drivers/index.md
  3.5/drivers/java-reference-collection-indexes.md
  3.5/drivers/java-reference-database-queries.md
  3.5/drivers/java-reference-database-stream-transactions.md
  3.5/drivers/java-reference-graph-edges.md
  3.5/drivers/java-reference-graph-vertices.md
  3.5/drivers/java-reference-graph.md
  3.5/drivers/java-reference-view-analyzers.md
  3.5/drivers/java-reference-view-arangosearch.md
  3.5/drivers/java-reference.md
  3.5/drivers/java.md
  3.5/drivers/js-reference-analyzer.md
  3.5/drivers/js-reference-collection.md
  3.5/drivers/js-reference-database-analyzer-access.md
  3.5/drivers/js-reference-database-graph-access.md
  3.5/drivers/js-reference-database-transactions.md
  3.5/drivers/js-reference-view.md
  3.5/drivers/js-reference.md
  3.5/drivers/spring-data-getting-started.md
  3.6/deployment-kubernetes-backup-policy-resource.md
  3.6/deployment-kubernetes-backup-resource.md
  3.6/deployment-kubernetes-deployment-resource.md
  3.6/deployment-kubernetes-helm.md
  3.6/deployment-kubernetes-metrics.md
  3.6/deployment-kubernetes.md
  3.6/drivers/index.md
  3.6/drivers/java-reference-collection-indexes.md
  3.6/drivers/java-reference-database-queries.md
  3.6/drivers/java-reference-database-stream-transactions.md
  3.6/drivers/java-reference-graph-edges.md
  3.6/drivers/java-reference-graph-vertices.md
  3.6/drivers/java-reference-graph.md
  3.6/drivers/java-reference-view-analyzers.md
  3.6/drivers/java-reference-view-arangosearch.md
  3.6/drivers/java-reference.md
  3.6/drivers/java.md
  3.6/drivers/js-reference-analyzer.md
  3.6/drivers/js-reference-collection.md
  3.6/drivers/js-reference-database-analyzer-access.md
  3.6/drivers/js-reference-database-graph-access.md
  3.6/drivers/js-reference-database-transactions.md
  3.6/drivers/js-reference-view.md
  3.6/drivers/js-reference.md
  3.6/drivers/spring-data-getting-started.md
  _data/3.5-drivers.yml
  _data/3.5-manual.yml
  _data/3.6-drivers.yml
  _data/3.6-manual.yml
Labels: 9 WIP
