Repository arangodb/docs, pull requests merged in 2019-09, with the labels that each got.

#164 HTTP Database API: Fix sentence
  3.5/http/database-notes-on-databases.md
  3.6/http/database-notes-on-databases.md
Labels: 1 Bug

#160 Update Known Issues and add 3.6 pages
  3.4/release-notes-known-issues34.md
  3.5/release-notes-known-issues34.md
  3.5/release-notes-known-issues35.md
  3.6/release-notes-36.md
  3.6/release-notes-known-issues34.md
  3.6/release-notes-known-issues35.md
  3.6/release-notes-known-issues36.md
  3.6/release-notes-new-features36.md
  3.6/release-notes-upgrading-changes36.md
  _data/3.6-manual.yml
Labels: 1 Bug

#157 Add --cluster.synchronous-replication-timeout-minimum option.
  3.4/programs-arangod-cluster.md
  3.5/programs-arangod-cluster.md
  3.6/programs-arangod-cluster.md
Labels: 1 Feature, 9 Ready to Merge

#159 Add TLS v1.3 as SSL protocol
  3.5/programs-arangod-ssl.md
  3.6/programs-arangod-ssl.md
Labels: 1 Feature

#170 RETURN DISTINCT does not change result order
  3.4/aql/examples-grouping.md
  3.4/aql/operations-collect.md
  3.4/aql/operations-return.md
  3.5/aql/examples-grouping.md
  3.5/aql/operations-collect.md
  3.5/aql/operations-return.md
  3.6/aql/examples-grouping.md
  3.6/aql/operations-collect.md
  3.6/aql/operations-return.md
Labels: 1 Bug

#171 Known issue: TTL indexes don't work for nested attributes
  3.5/indexing-ttl.md
  3.5/release-notes-known-issues35.md
  3.6/indexing-ttl.md
Labels: 1 Bug

#174 Known issue: http.keep-alive-timeout is ignored in 3.4.x
  3.4/release-notes-known-issues34.md
  3.5/release-notes-known-issues34.md
  3.6/release-notes-known-issues34.md
Labels: 1 Bug, 9 Ready to Merge
