Repository arangodb/docs, pull requests merged in 2019-07, with the labels that each got.

#97 Add version info for rocksdb.total-write-buffer-size, remove "Hidden" remark
  3.2/administration-configuration-rocks-db.md
  3.3/administration-configuration-rocks-db.md
  3.4/programs-arangod-rocksdb.md
  3.5/programs-arangod-rocksdb.md
Labels: 1 Bug

#100 Advice io1 storage / EC2 I3 instances for AWS
  3.4/deployment-cloud-aws.md
  3.5/deployment-cloud-aws.md
Labels: 1 Feature

#93 Add concise Smart Joins description
  3.4/smartjoins.md
  3.5/release-notes-new-features35.md
  3.5/smartjoins.md
  _data/3.4-manual.yml
  _data/3.5-manual.yml
Labels: 1 Feature

#86 Added hint block for Starter Removal procedure
  3.4/administration-starter-removal.md
  3.5/administration-starter-removal.md
Labels: 1 Feature

#25 Add 'Reducing the Memory Footprint' page
  3.5/images/performance_graph.png
  3.5/tutorials-reduce-memory-footprint.md
  3.5/tutorials.md
  _data/3.5-manual.yml
Labels: 9 WIP

#27 Update getting-started-installation.md
  3.4/getting-started-installation.md
  3.5/getting-started-installation.md
Labels: 9 CLA available

#101 Minor grammatical fix
  3.3/administration-configuration-compaction.md
  3.3/aql/tutorial-crud.md
  3.3/cookbook/administration-migrate2-8to3-0.md
  3.3/cookbook/compiling-jemalloc.md
  3.3/cookbook/monitoring-slave-status.md
  3.3/deployment-agency.md
  3.3/deployment-arango-dbstarter.md
  3.3/foxx-dependencies.md
  3.3/foxx-graph-ql.md
  3.3/foxx-migrating2x-controllers-response.md
  3.3/foxx-migrating2x-controllers.md
  3.3/foxx-migrating2x-repositories.md
  3.3/foxx-migrating2x-wayback.md
  3.3/foxx-migrating2x.md
  3.3/foxx-testing.md
  3.3/getting-started-arangosh.md
  3.3/graphs-pregel.md
  3.3/release-notes-new-features32.md
  3.3/release-notes-upgrading-changes31.md
  3.3/release-notes-upgrading-changes32.md
  3.4/aql/tutorial-crud.md
  3.4/architecture-deployment-modes-active-failover-architecture.md
  3.4/cookbook/compiling-jemalloc.md
  3.4/cookbook/monitoring-slave-status.md
  3.4/deployment-standalone-agency.md
  3.4/foxx-migrating2x-controllers-response.md
  3.4/foxx-migrating2x-controllers.md
  3.4/foxx-migrating2x-repositories.md
  3.4/foxx-migrating2x-wayback.md
  3.4/foxx-reference-modules-graph-ql.md
  3.4/graphs-pregel.md
  3.4/programs-foxx-cli-details.md
  3.4/release-notes-new-features32.md
  3.4/release-notes-upgrading-changes31.md
  3.4/release-notes-upgrading-changes32.md
  3.5/aql/tutorial-crud.md
  3.5/architecture-deployment-modes-active-failover-architecture.md
  3.5/cookbook/compiling-jemalloc.md
  3.5/cookbook/monitoring-slave-status.md
  3.5/deployment-standalone-agency.md
  3.5/foxx-migrating2x-controllers-response.md
  3.5/foxx-migrating2x-controllers.md
  3.5/foxx-migrating2x-repositories.md
  3.5/foxx-migrating2x-wayback.md
  3.5/foxx-reference-modules-graph-ql.md
  3.5/graphs-pregel.md
  3.5/programs-foxx-cli-details.md
  3.5/release-notes-new-features32.md
  3.5/release-notes-upgrading-changes31.md
  3.5/release-notes-upgrading-changes32.md
Labels: 1 Bug, 9 CLA available

#103 Removed deprecation info
  3.5/release-notes-upgrading-changes35.md
Labels: 9 Ready to Merge

#107 Add 2 missing ways to call COLLECT.
  3.3/aql/operations-collect.md
  3.4/aql/operations-collect.md
  3.5/aql/operations-collect.md
Labels: 1 Bug

#108 added minReplicationFactor
  3.5/architecture-replication.md
  3.5/data-modeling-collections-database-methods.md
  3.5/release-notes-new-features35.md
Labels: 1 Feature

#119 Fix free-text links
  3.4/drivers/index.md
  3.5/architecture-storage-engines.md
  3.5/cookbook/cloud-node-js-docker.md
  3.5/cookbook/compiling-debian.md
  3.5/cookbook/compiling-windows.md
  3.5/cookbook/index.md
  3.5/cookbook/use-cases-exporting-data.md
  3.5/deployment-active-failover-manual-start.md
  3.5/deployment-active-failover-using-the-starter.md
  3.5/deployment-cluster-manual-start.md
  3.5/deployment-cluster-using-the-starter.md
  3.5/deployment-single-instance-manual-start.md
  3.5/deployment-single-instance-using-the-starter.md
  3.5/drivers/go-getting-started.md
  3.5/drivers/index.md
  3.5/drivers/java-reference-serialization.md
  3.5/getting-started-web-interface.md
  3.5/graphs-pregel.md
  3.5/http/general.md
  3.5/http/repairs.md
  3.5/installation.md
  3.5/release-notes-new-features26.md
  3.5/release-notes-upgrading-changes34.md
  3.5/security-security-options.md
  3.5/upgrading-manually-active-failover.md
  3.5/upgrading-manually-cluster.md
  3.5/upgrading-starter.md
Labels: 1 Bug, 9 WIP

#110 Remove things related to mesos and dcos
  3.5/architecture-deployment-modes-cluster-architecture.md
  3.5/architecture-deployment-modes-cluster-data-models.md
  3.5/cookbook/cloud.md
  3.5/deployment-cluster-mesos.md
  3.5/deployment-cluster.md
  3.5/deployment-dc2-dc-cluster.md
  3.5/deployment-dcos-cluster-mesos.md
  3.5/deployment-dcos-mesos-containers.md
  3.5/deployment-dcos.md
  3.5/deployment-technology.md
  3.5/deployment.md
  3.5/programs-starter-architecture.md
  _data/3.5-manual.yml
Labels: 9 Review Required

#121 add REST API GET /_api/transaction
  3.5/http/transaction-stream-transaction.md
Labels: 1 Feature, 9 WIP

#120 AQL MATCHES(): Add remarks about null and undefined
  3.4/aql/functions-document.md
  3.5/aql/functions-document.md
Labels: 1 Question

#127 Starter: Link from admin to programs, fix typos
  3.4/administration-starter.md
  3.4/deployment-active-failover-using-the-starter.md
  3.4/deployment-cluster-using-the-starter.md
  3.4/deployment-single-instance-using-the-starter.md
  3.4/programs-starter.md
  3.4/tutorials-starter.md
  3.5/administration-starter.md
  3.5/deployment-active-failover-using-the-starter.md
  3.5/deployment-cluster-using-the-starter.md
  3.5/deployment-single-instance-using-the-starter.md
  3.5/programs-starter.md
  3.5/tutorials-starter.md
Labels: 1 Feature
