Repository arangodb/docs, pull requests merged in 2019-11, with the labels that each got.

#115 Cleanup config / Upgrade to Jekyll 4.0
  Gemfile
  Gemfile.lock
  _config.yml
Labels: 1 Feature

#150 ArangoSearch refactor (part 2)
  3.5/aql/functions-arangosearch.md
  3.5/arangosearch-analyzers.md
  3.5/arangosearch-views.md
  3.6/aql/functions-arangosearch.md
  3.6/arangosearch-analyzers.md
  3.6/arangosearch-views.md
Labels: 1 Feature

#218 Add new-features-3.6 entry for AQL Subquery Splicing
  3.6/aql/execution-and-performance-optimizer.md
  3.6/release-notes-new-features36.md
Labels: 1 Feature

#228 Doc - Fixed typo in Community Detection section
  3.5/graphs-pregel.md
  3.6/graphs-pregel.md
Labels: 1 Bug, 9 CLA available

#236 Remove GATHER and REMOTE from the subquery splicing naughty list
  3.6/aql/execution-and-performance-optimizer.md
  3.6/release-notes-new-features36.md
Labels: 1 Bug

#233 Clarified two things about splice-subqueries
  3.6/aql/execution-and-performance-optimizer.md
  3.6/release-notes-new-features36.md
Labels: 9 Review Required
