Repository arangodb/docs, pull requests merged in 2019-08, with the labels that each got.

#126 add options to disable the foxx store / api
  3.4/security-security-options.md
  3.4/security.md
  _data/3.4-manual.yml
Labels: 1 Feature

#131 Version placeholder in macOS commands
  3.4/installation-mac-osx.md
  3.5/installation-mac-osx.md
Labels: 1 Bug

#135 Add note about polygon limitation in GeoJSON functionality.
  3.4/indexing-geo.md
  3.5/indexing-geo.md
Labels: 1 Bug

#104 k Shortest Paths example graph
  3.5/aql/graphs-kshortest-paths.md
  3.5/graphs.md
Labels: 1 Feature

#136 Add docs for new distance ellipsoid
  3.5/aql/functions-geo.md
Labels: 1 Feature, 9 Review Required

#116 Temporary script for manual sitemap generation
  _config.yml
  sitemap.rb
Labels: 1 Feature

#89 ArangoSearch refactor
  3.0/aql/functions-string.md
  3.1/aql/functions-string.md
  3.2/aql/functions-string.md
  3.3/aql/functions-string.md
  3.4/aql/functions-string.md
  3.4/aql/views-arango-search.md
  3.4/data-modeling-views-database-methods.md
  3.4/data-modeling-views-view-methods.md
  3.4/views-arango-search-detailed-overview.md
  3.5/analyzers.md
  3.5/appendix-glossary.md
  3.5/appendix-java-script-modules-analyzers.md
  3.5/appendix-java-script-modules.md
  3.5/aql/execution-and-performance-query-cache.md
  3.5/aql/functions-arangosearch.md
  3.5/aql/functions-string.md
  3.5/aql/operations-filter.md
  3.5/aql/operations-for.md
  3.5/aql/operations-search.md
  3.5/aql/operations.md
  3.5/aql/views-arango-search.md
  3.5/aql/views.md
  3.5/arangosearch-analyzers.md
  3.5/arangosearch-examples.md
  3.5/arangosearch-views.md
  3.5/arangosearch.md
  3.5/data-modeling-naming-conventions-collection-and-view-names.md
  3.5/data-modeling-views-database-methods.md
  3.5/data-modeling-views-view-methods.md
  3.5/data-modeling-views.md
  3.5/drivers/java-reference-database-view-access.md
  3.5/drivers/java-reference-view-arangosearch.md
  3.5/drivers/java-reference-view-view-manipulation.md
  3.5/drivers/java-reference-view.md
  3.5/drivers/java-reference.md
  3.5/drivers/js-reference-database-view-access.md
  3.5/drivers/js-reference-view-manipulation.md
  3.5/highlights.md
  3.5/http/analyzers.md
  3.5/http/views-arango-search.md
  3.5/http/views-arangosearch.md
  3.5/http/views-creating.md
  3.5/http/views-dropping.md
  3.5/http/views-getting.md
  3.5/http/views-modifying.md
  3.5/http/views.md
  3.5/indexing-index-basics.md
  3.5/release-notes-known-issues35.md
  3.5/release-notes-new-features34.md
  3.5/release-notes-new-features35.md
  3.5/release-notes-upgrading-changes35.md
  3.5/upgrading-version-specific-upgrading34.md
  3.5/views-arango-search-analyzers.md
  3.5/views-arango-search-detailed-overview.md
  3.5/views-arango-search-scorers.md
  3.5/views-arango-search.md
  _data/3.5-aql.yml
  _data/3.5-drivers.yml
  _data/3.5-http.yml
  _data/3.5-manual.yml
Labels: 1 Feature

#129 Release Notes 3.5: Add some links to other chapters
  3.5/release-notes-new-features35.md
Labels: 1 Feature, 9 Review Required

#111 Add minReplicationFactor docs for Java driver
  3.5/drivers/java-reference-collection-collection-manipulation.md
  3.5/drivers/java-reference-graph.md
Labels: 1 Feature

#148 Typo fixes
  3.5/release-notes-new-features35.md
  3.6/release-notes-new-features35.md
Labels: 1 Bug

#154 Add note about fixing user restrictions for streaming transactions.
  3.5/release-notes-known-issues35.md
  3.6/release-notes-known-issues35.md
Labels: 9 Ready to Merge

#151 Some minor fixes
  3.5/highlights.md
  3.5/index.md
  3.6/highlights.md
  3.6/index.md
Labels: 1 Bug

#156 Added SUSE in OSTuning section
  3.4/installation-linux-ostuning-scripts.md
  3.5/installation-linux-ostuning-scripts.md
  3.6/installation-linux-ostuning-scripts.md
Labels: 9 Ready to Merge
