Repository arangodb/docs, pull requests merged in 2020-06, with the labels that each got.

#78 Foxx: Docs for securitySchemes
  3.7/foxx-reference-routers-endpoints.md
  3.7/foxx-reference-routers.md
Labels: 1 Feature

#450 added spark write method options
  3.4/drivers/spark-connector-reference-java.md
  3.4/drivers/spark-connector-reference-scala.md
  3.5/drivers/spark-connector-reference-java.md
  3.5/drivers/spark-connector-reference-scala.md
  3.6/drivers/spark-connector-reference-java.md
  3.6/drivers/spark-connector-reference-scala.md
  3.7/drivers/spark-connector-reference-java.md
  3.7/drivers/spark-connector-reference-scala.md
Labels: 1 Feature

#456 Document Override total memory in Operator ArangoDeployment
  3.6/deployment-kubernetes-deployment-resource.md
  3.7/deployment-kubernetes-deployment-resource.md
Labels: 1 Feature

#448 update docs for crash handler v2
  3.7/programs-arangod-env-vars.md
  3.7/release-notes-new-features37.md
  3.7/troubleshooting-arangod.md
Labels: 1 Feature

#460 Arangoimport: Only UTF-8 without BOM is supported
  3.5/programs-arangoimport-details.md
  3.6/programs-arangoimport-details.md
  3.7/programs-arangoimport-details.md
Labels: 1 Question

#459 Feature/add more 37 features
  3.7/highlights.md
  3.7/release-notes-api-changes37.md
  3.7/release-notes-new-features37.md
  3.7/release-notes-upgrading-changes37.md
Labels: 1 Feature

#449 Add new RocksDB options for controlling index and filter block caching
  3.7/release-notes-new-features37.md
Labels: 1 Feature, 9 WIP

#462 Add missing arangosh options
  3.5/aql/invocation-with-arangosh.md
  3.6/aql/invocation-with-arangosh.md
  3.7/aql/invocation-with-arangosh.md
Labels: 1 Bug

#463 Update 3.7 Highlights
  3.7/highlights.md
Labels: 1 Feature

#465 add traversal parallelism
  3.7/aql/graphs-traversals.md
  3.7/highlights.md
  3.7/release-notes-new-features37.md
Labels: 1 Feature

#468 Update functions-arangosearch.md
  3.7/aql/functions-arangosearch.md
Labels: 1 Bug

#473 remove replication changes from the docs for now
  3.7/release-notes-new-features37.md
  3.8/release-notes-new-features37.md
Labels: 1 Feature

#482 Fix optimizer rule name for scattering SatelliteGraphs
  3.7/aql/execution-and-performance-optimizer.md
  3.8/aql/execution-and-performance-optimizer.md
Labels: 1 Bug
