Repository arangodb/docs, pull requests merged in 2020-12, with the labels that each got.

#582 PHP driver: Fix updateById()/replaceById() method's description.
  3.7/drivers/php-tutorial.md
Labels: 9 CLA available

#571 feature/arangosearch-s2
  3.7/aql/functions-arangosearch.md
  3.8/aql/functions-arangosearch.md
  3.8/aql/functions-geo.md
  3.8/arangosearch-analyzers.md
  3.8/highlights.md
  3.8/release-notes-new-features38.md
Labels: 1 Feature

#597 Known issue: db not found when slow queries are accessed after db creation
  3.6/release-notes-known-issues36.md
  3.7/release-notes-known-issues37.md
Labels: 1 Bug

#564 WINDOW operation
  3.3/aql/operations.md
  3.8/aql/fundamentals-syntax.md
  3.8/aql/operations-window.md
  3.8/aql/operations.md
  3.8/highlights.md
  3.8/release-notes-new-features38.md
  3.8/release-notes-upgrading-changes38.md
  _data/3.8-aql.yml
Labels: 1 Feature

#596 Cluster support for collection.checksum() method
  3.8/data-modeling-collections-collection-methods.md
  3.8/release-notes-new-features38.md
Labels: 1 Feature
