Repository arangodb/docs, pull requests merged in 2020-04, with the labels that each got.

#395 AQL Interleave.
  3.7/aql/functions-array.md
Labels: 1 Feature

#401 phrase in_range
  3.7/aql/functions-arangosearch.md
Labels: 1 Feature

#405 add overwrite mode docs
  3.4/aql/operations-insert.md
  3.4/aql/operations-replace.md
  3.4/aql/operations-update.md
  3.4/aql/operations-upsert.md
  3.5/aql/operations-insert.md
  3.5/aql/operations-replace.md
  3.5/aql/operations-update.md
  3.5/aql/operations-upsert.md
  3.6/aql/operations-insert.md
  3.6/aql/operations-replace.md
  3.6/aql/operations-update.md
  3.6/aql/operations-upsert.md
  3.7/aql/operations-insert.md
  3.7/aql/operations-replace.md
  3.7/aql/operations-update.md
  3.7/aql/operations-upsert.md
  3.7/data-modeling-documents-document-methods.md
  3.7/release-notes-api-changes37.md
Labels: 1 Feature

#404 add issue about collection properties update
  3.7/release-notes-known-issues37.md
Labels: 1 Bug

#398 java-reference-typed-analyzers
  3.6/drivers/java-reference-view-analyzers.md
  3.7/drivers/java-reference-view-analyzers.md
Labels: 1 Feature

#402 Feature/view store compression properties
  3.7/aql/operations-search.md
  3.7/arangosearch-views.md
  3.7/highlights.md
  3.7/release-notes-new-features37.md
Labels: 1 Feature

#408 Allow external links in navigation
  3.6/drivers/spring-data.md
  3.7/drivers/spring-data.md
  _data/3.6-drivers.yml
  _data/3.7-drivers.yml
  _plugins/NavigationTag.rb
  js/site.js
Labels: 1 Feature

#403 added new optimizer rule, adjusted remove-satellite-joins
  3.7/aql/execution-and-performance-optimizer.md
Labels: 1 Feature

#414 Remove mention of scatter-arangosearch-view-in-cluster
  3.7/aql/execution-and-performance-optimizer.md
Labels: 9 Ready to Merge

#400 Feature/satellite graphs 2
  3.7/graphs-satellite-graphs-details.md
  3.7/graphs-satellite-graphs-management.md
  3.7/graphs-satellite-graphs.md
  3.7/http/gharial.md
  _data/3.7-manual.yml
Labels: 1 Feature

#412 Improve crypto.createNonce(), .checkAndMarkNonce()
  3.3/appendix-java-script-modules-crypto.md
  3.4/appendix-java-script-modules-crypto.md
  3.5/appendix-java-script-modules-crypto.md
  3.6/appendix-java-script-modules-crypto.md
  3.7/appendix-java-script-modules-crypto.md
Labels: 1 Bug
