Repository arangodb/docs, pull requests merged in 2020-11, with the labels that each got.

#568 added aql analyzer description
  3.8/arangosearch-analyzers.md
  3.8/generated/Examples/analyzerAqlCollapse.generated
  3.8/generated/Examples/analyzerAqlConcat.generated
  3.8/generated/Examples/analyzerAqlFilter.generated
  3.8/generated/Examples/analyzerAqlFilterNull.generated
  3.8/generated/Examples/analyzerAqlSoundex.generated
  3.8/highlights.md
  3.8/release-notes-new-features38.md
Labels: 1 Feature

#592 Add resolve_symlink filter to get relative source file path
  _layouts/default.html
  _plugins/ExtraFilters.rb
Labels: 1 Bug

#588 Fix broken links
  3.3/appendix-java-script-modules.md
  3.3/foxx-graph-ql.md
  3.3/release-notes-new-features21.md
  3.3/release-notes-new-features24.md
  3.3/release-notes-new-features26.md
  3.4/appendix-java-script-modules.md
  3.4/foxx-reference-modules-graph-ql.md
  3.4/release-notes-new-features21.md
  3.4/release-notes-new-features24.md
  3.4/release-notes-new-features26.md
  3.5/appendix-java-script-modules.md
  3.5/foxx-reference-modules-graph-ql.md
  3.5/programs-arangobackup-examples.md
  3.6/appendix-java-script-modules.md
  3.6/foxx-reference-modules-graph-ql.md
  3.6/programs-arangobackup-examples.md
  3.7/appendix-java-script-modules.md
  3.7/foxx-reference-modules-graph-ql.md
  3.7/programs-arangobackup-examples.md
  3.7/release-notes-new-features21.md
  3.7/release-notes-new-features24.md
  3.7/release-notes-new-features26.md
  3.8/foxx-reference-modules-graph-ql.md
  3.8/programs-arangobackup-examples.md
Labels: 9 CLA available
