Repository arangodb/docs, pull requests merged in 2020-01, with the labels that each got.

#305 Audit EE feature not available in Oasis
  3.4/security-auditing-audit-configuration.md
  3.4/security-auditing-audit-events.md
  3.4/security-auditing.md
  3.5/security-auditing-audit-configuration.md
  3.5/security-auditing-audit-events.md
  3.5/security-auditing.md
  3.6/security-auditing-audit-configuration.md
  3.6/security-auditing-audit-events.md
  3.6/security-auditing.md
  3.7/security-auditing-audit-configuration.md
  3.7/security-auditing-audit-events.md
  3.7/security-auditing.md
Labels: 1 Bug

#304 Add docs for kube-arangodb 0.4.3 version
  3.4/deployment-kubernetes-deployment-resource.md
  3.5/deployment-kubernetes-deployment-resource.md
  3.6/deployment-kubernetes-deployment-resource.md
  3.7/deployment-kubernetes-deployment-resource.md
Labels: 1 Feature

#313 Added documentation about queries with options
  3.7/appendix-java-script-modules-arango-db.md
  3.7/foxx-guides-queries.md
  3.7/release-notes-new-features37.md
Labels: 1 Feature, 9 Ready to Merge

#321 Add documentation for TLS cert rotation.
  3.7/generated/allComments.txt
  3.7/generated/api-docs.json
  3.7/http/administration-and-monitoring.md
Labels: 1 Feature
