Repository arangodb/docs, pull requests merged in 2020-05, with the labels that each got.

#426 Update tutorial-filter.md
  3.3/aql/tutorial-filter.md
  3.4/aql/tutorial-filter.md
  3.5/aql/tutorial-filter.md
  3.6/aql/tutorial-filter.md
Labels: 1 Bug

#423 ArangoSearch example fix
  3.4/views-arango-search-getting-started.md
  3.5/aql/operations-search.md
  3.5/arangosearch-examples.md
  3.6/aql/operations-search.md
  3.6/arangosearch-examples.md
  3.7/aql/operations-search.md
  3.7/arangosearch-examples.md
Labels: 1 Bug

#433 Fix enumeration for overwriteMode.
  3.7/aql/operations-insert.md
Labels: 1 Bug

#436 Cluster admin: replicationFactor and DB-Server count
  3.4/administration-cluster.md
  3.5/administration-cluster.md
  3.6/administration-cluster.md
  3.7/administration-cluster.md
Labels: 1 Bug

#437 optimizer rule remove-distribute-nodes
  3.7/aql/execution-and-performance-optimizer.md
Labels: 1 Feature

#435 Document push-subqueries-to-dbserver rule
  3.7/aql/execution-and-performance-optimizer.md
Labels: 1 Feature

#424 added docs for "optimize-count" optimizer rule
  3.7/aql/execution-and-performance-optimizer.md
  3.7/release-notes-new-features37.md
Labels: 1 Feature

#441 Add `.local` problem to known issues.
  3.4/release-notes-known-issues34.md
  3.5/release-notes-known-issues34.md
  3.5/release-notes-known-issues35.md
  3.6/release-notes-known-issues34.md
  3.6/release-notes-known-issues35.md
  3.6/release-notes-known-issues36.md
  3.7/release-notes-known-issues34.md
  3.7/release-notes-known-issues35.md
  3.7/release-notes-known-issues36.md
Labels: 1 Bug

#427 added disjoint smart graph documentation to release notes api changes
  3.7/release-notes-api-changes37.md
Labels: 1 Feature

#428 added disjoint smart graph documentation to release notes new features
  3.7/release-notes-new-features37.md
Labels: 9 Ready to Merge

#429 Disjoint SmartGraphs
  3.7/graphs-smart-graphs-management.md
  3.7/graphs-smart-graphs.md
  3.7/highlights.md
  3.7/release-notes-new-features37.md
Labels: 1 Feature

#332 Encryption at Rest key rotation
  3.7/http/administration-and-monitoring.md
  3.7/release-notes-new-features37.md
  3.7/security-encryption.md
Labels: 1 Feature

#191 add release notes and doc for smart-joining views
  3.6/release-notes-new-features36.md
  3.6/smartjoins.md
  3.7/release-notes-new-features36.md
  3.7/smartjoins.md
Labels: 1 Feature

#231 Backport query timeout feature to v3.5.4
  3.5/aql/invocation-with-arangosh.md
  3.6/release-notes-new-features36.md
  3.7/release-notes-new-features36.md
Labels: 1 Feature

#438 update LEVENSHTEIN_MATCH description
  3.7/aql/functions-arangosearch.md
Labels: 1 Feature

#446 Adjust encryption key rotation
  3.7/release-notes-new-features37.md
  3.7/security-encryption.md
Labels: 1 Feature

#442 ES-554 known issue
  3.5/release-notes-known-issues35.md
  3.6/release-notes-known-issues35.md
  3.6/release-notes-known-issues36.md
  3.7/release-notes-known-issues35.md
  3.7/release-notes-known-issues36.md
  3.7/release-notes-known-issues37.md
Labels: 1 Bug
