Repository arangodb/docs, pull requests merged in 2021-04, with the labels that each got.

#664 add returnType description for AQL analyzer
  3.8/arangosearch-analyzers.md
Labels: 1 Feature

#681 Add arangovpack to programs
  3.9/generated/arangovpack-options.json
  3.9/programs-arangovpack-options.md
  3.9/programs-arangovpack.md
  3.9/programs.md
  3.9/release-notes-new-features39.md
  README.md
  _data/3.9-manual.yml
  _data/3.9-program-options-arangovpack.json
Labels: 1 Feature

#683 Add --ldap2.* page for arangod
  3.6/programs-arangod-ldap.md
  3.7/programs-arangod-ldap.md
  3.8/programs-arangod-ldap.md
  3.9/programs-arangod-ldap.md
  _includes/program-option.html
  _plugins/OptionsBySectionFilter.rb
Labels: 1 Feature

#687 Known issue: exclusive transactions in cluster (3.6 only)
  3.6/release-notes-known-issues36.md
Labels: 1 Bug

#686 Add endpoint `POST /_api/cursor/<cursor-id>`
  3.7/http/aql-query-cursor-accessing-cursors.md
  3.8/http/aql-query-cursor-accessing-cursors.md
  3.8/http/aql-query-cursor-query-results.md
  3.8/release-notes-api-changes38.md
  3.9/appendix-deprecated.md
  3.9/http/aql-query-cursor-accessing-cursors.md
  3.9/http/aql-query-cursor-query-results.md
Labels: 9 Ready to Merge
