Repository arangodb/docs, pull requests merged in 2021-11, with the labels that each got.

#797 Add missing description for --server.maximal-threads default value
  3.10/programs-arangod-server.md
  3.6/programs-arangod-server.md
  3.7/programs-arangod-server.md
  3.8/programs-arangod-server.md
  3.9/programs-arangod-server.md
Labels: 1 Bug, hacktoberfest-accepted

#790 New Enterprise Edition license management
  3.9/administration-license.md
  3.9/administration.md
  3.9/http/license.md
  3.9/release-notes-api-changes39.md
  3.9/release-notes-new-features39.md
  _data/3.9-http.yml
  _data/3.9-manual.yml
Labels: 9 Waiting for Upstream Merge

#798 Better introduction for COLLECT
  3.10/aql/operations-collect.md
  3.7/aql/operations-collect.md
  3.8/aql/operations-collect.md
  3.9/aql/operations-collect.md
Labels: 9 CLA available, hacktoberfest-accepted

#802 Documentation for BTS-623 and 3.9 backport
  3.10/programs-arangod-audit.md
  3.10/security-auditing-audit-configuration.md
  3.9/programs-arangod-audit.md
  3.9/security-auditing-audit-configuration.md
Labels: 1 Feature
