Repository arangodb/docs, pull requests merged in 2021-03, with the labels that each got.

#643 allow dynamic logfile names for testing
  3.7/programs-arangod-audit.md
  3.7/programs-arangod-log.md
Labels: 1 Feature

#642 document TZ_DATA variable
  3.8/release-notes-api-changes38.md
Labels: 1 Feature

#645 Correct statements about value comparisons
  3.4/aql/fundamentals-data-types.md
  3.4/aql/operators.md
  3.5/aql/fundamentals-data-types.md
  3.5/aql/operators.md
  3.6/aql/fundamentals-data-types.md
  3.6/aql/operators.md
  3.7/aql/fundamentals-data-types.md
  3.7/aql/operators.md
  3.8/aql/fundamentals-data-types.md
  3.8/aql/operators.md
Labels: 1 Bug

#605 documentation for DATE_TIMEZONE(S) and zoneinfo switch
  3.8/aql/functions-date.md
  3.8/release-notes-new-features38.md
Labels: 1 Feature

#630 Documentation of K_Paths feature
  3.8/aql/execution-and-performance-optimizer.md
  3.8/aql/fundamentals-syntax.md
  3.8/aql/graphs-k-paths.md
  3.8/aql/graphs-kshortest-paths.md
  3.8/generated/Examples/GRAPHKP_01_Aberdeen_to_London.generated
  3.8/generated/Examples/GRAPHKP_01_create_graph.generated
  3.8/generated/Examples/GRAPHKP_02_Aberdeen_to_Toronto.generated
  3.8/generated/Examples/GRAPHKP_99_drop_graph.generated
  3.8/generated/allComments.txt
  3.8/release-notes-new-features38.md
  _data/3.8-aql.yml
Labels: 9 Ready to Merge

#654 Feature/stopwords analyzer
  3.8/arangosearch-analyzers.md
  3.8/generated/Examples/analyzerPipelineStopwords.generated
  3.8/generated/Examples/analyzerStopwords.generated
  3.8/generated/allComments.txt
  3.8/highlights.md
  3.8/release-notes-new-features38.md
Labels: 1 Feature
