Repository arangodb/docs, pull requests merged in 2021-09, with the labels that each got.

#764 deprecate several extra arangobench testcases
  3.9/programs-arangobench.md
Labels: 9 Waiting for Upstream Merge

#766 Change term vocbase to database
  3.7/data-modeling-collections-database-methods.md
  3.8/data-modeling-collections-database-methods.md
  3.9/data-modeling-collections-database-methods.md
Labels: 9 CLA available

#760 APM-70: PRUNE with output variable
  3.9/aql/graphs-traversals.md
  3.9/release-notes-new-features39.md
Labels: 9 Ready to Merge

#767 Add `--datatype` option to arangoimport
  3.9/programs-arangoimport-examples-csv.md
  3.9/release-notes-new-features39.md
Labels: 9 Ready to Merge

#754 APM-60: Extended database names
  3.9/appendix-glossary.md
  3.9/data-modeling-naming-conventions-database-names.md
  3.9/http/database-notes-on-databases.md
  3.9/http/database.md
  3.9/release-notes-api-changes39.md
  3.9/release-notes-new-features39.md
  3.9/release-notes-upgrading-changes39.md
Labels: 1 Feature

#758 Add ballpark numbers for DB, collection & shard counts in cluster
  3.7/architecture-deployment-modes-cluster-limitations.md
  3.8/architecture-deployment-modes-cluster-limitations.md
  3.9/architecture-deployment-modes-cluster-limitations.md
Labels: 1 Question
