Repository arangodb/docs, pull requests merged in 2021-07, with the labels that each got.

#718 added info about new decay functions
  3.9/aql/functions-numeric.md
  3.9/release-notes-new-features39.md
Labels: 1 Feature

#723 Reviewing typos and a missing word.
  drivers/js-getting-started.md
Labels: 9 CLA available

#716 Soft coordinator shutdown documentation
  3.7/http/miscellaneous-functions.md
  3.8/http/miscellaneous-functions.md
  3.9/generated/allComments.txt
  3.9/generated/api-docs.json
  3.9/http/miscellaneous-functions.md
Labels: 1 Feature

#729 Add known issue for LOGS view not loading the 2nd time
  3.8/release-notes-known-issues38.md
Labels: 1 Bug

#728 Add ArangoSearch Geo Search Examples
  3.7/arangosearch-geospatial-search.md
  3.7/arangosearch.md
  3.8/arangosearch-example-datasets.md
  3.8/arangosearch-geospatial-search.md
  3.8/arangosearch.md
  3.8/images/arangosearch-geo-points-in-polygon.png
  3.8/images/arangosearch-geo-polygons-in-polygon.png
  3.8/images/arangosearch-geo-polygons-intersecting-polygon.png
  3.9/arangosearch-example-datasets.md
  3.9/arangosearch-geospatial-search.md
  3.9/arangosearch.md
  3.9/images/arangosearch-geo-points-in-polygon.png
  3.9/images/arangosearch-geo-polygons-in-polygon.png
  3.9/images/arangosearch-geo-polygons-intersecting-polygon.png
  _data/3.7-manual.yml
  _data/3.8-manual.yml
  _data/3.9-manual.yml
Labels: 1 Feature

#731 fix login example
  3.6/foxx-guides-auth.md
  3.7/foxx-guides-auth.md
  3.8/foxx-guides-auth.md
  3.9/foxx-guides-auth.md
Labels: 9 CLA available
