Repository arangodb/docs, pull requests merged in 2022-03, with the labels that each got.

#864 add more indexHints: `disableIndex` and `maxProjections`
  3.10/aql/execution-and-performance-optimizer.md
  3.10/aql/operations-for.md
  3.9/aql/execution-and-performance-optimizer.md
  3.9/aql/operations-for.md
  3.9/release-notes-new-features39.md
Labels: cla-signed

#926 BTS-793 | Add how SHA256 hash of download can be checked
  3.10/installation-linux.md
  3.10/installation-mac-osx.md
  3.10/installation-windows.md
  3.9/installation-linux.md
  3.9/installation-mac-osx.md
  3.9/installation-windows.md
Labels: 9 Ready to Merge

#937 OAS-4513 | Warn about root credential usage / root password rotation feature
  oasis/deployments.md
  oasis/images/oasis-deployment-password-rotation.png
Labels: 9 Ready to Merge

#947 Added documentation for optimizer-rules-getter
  3.10/release-notes-api-changes310.md
  3.10/release-notes-new-features310.md
Labels: 9 Ready to Merge

#956 Update indexing-which-index.md
  3.10/indexing-which-index.md
  3.7/indexing-which-index.md
  3.8/indexing-which-index.md
  3.9/indexing-which-index.md
Labels: 9 CLA available, 9 Ready to Merge

#960 TTL index expects Unix timestamp in seconds
  3.10/indexing-index-basics.md
  3.10/indexing-ttl.md
  3.7/indexing-index-basics.md
  3.7/indexing-ttl.md
  3.8/indexing-index-basics.md
  3.8/indexing-ttl.md
  3.9/indexing-index-basics.md
  3.9/indexing-ttl.md
Labels: 9 Ready to Merge, 1 Bug

#946 icu-language option
  3.10/programs-arangod-general.md
  3.3/administration-configuration-general-arangod.md
  3.4/programs-arangod-global.md
  3.5/programs-arangod-global.md
  3.6/programs-arangod-general.md
  3.7/programs-arangod-general.md
  3.8/programs-arangod-general.md
  3.9/programs-arangod-general.md
  3.9/release-notes-new-features39.md
Labels: 9 Ready to Merge

#966 mention zlib library upgrade
  3.10/release-notes-new-features310.md
Labels: 9 Ready to Merge
