Repository arangodb/docs, pull requests merged in 2022-01, with the labels that each got.

#863 BTS-707: more support-info permissions more sensible
  3.10/security-security-options.md
  3.9/release-notes-api-changes39.md
  3.9/security-security-options.md
Labels: cla-signed

#865 slightly improve documentation for vector functions
  3.10/aql/functions-numeric.md
  3.9/aql/functions-numeric.md
Labels: cla-signed

#867 Deprecate leader/follower deployment mode
  3.10/administration-leader-follower-database-setup.md
  3.10/administration-leader-follower-initialize-from-backup.md
  3.10/administration-leader-follower-replication-applier.md
  3.10/administration-leader-follower-server-level-setup.md
  3.10/administration-leader-follower-setting-up.md
  3.10/administration-leader-follower-syncing-collections.md
  3.10/administration-leader-follower.md
  3.10/administration.md
  3.10/appendix-java-script-modules.md
  3.10/architecture-deployment-modes-active-failover-architecture.md
  3.10/architecture-deployment-modes-leader-follower-architecture.md
  3.10/architecture-deployment-modes-leader-follower-limitations.md
  3.10/architecture-deployment-modes-leader-follower.md
  3.10/architecture-deployment-modes.md
  3.10/architecture-replication.md
  3.10/data-modeling-databases-notes.md
  3.10/deployment-leader-follower-manual-start.md
  3.10/deployment-leader-follower.md
  3.10/deployment-manually.md
  3.10/deployment-modes.md
  3.10/deployment.md
  3.10/highlights.md
  3.10/index.md
  3.10/installation-linux.md
  3.10/installation-windows.md
  3.10/programs-arangodump-limitations.md
  3.10/programs-arangodump.md
  3.10/scaling.md
  3.7/release-notes-new-features33.md
  3.9/administration-leader-follower-database-setup.md
  3.9/administration-leader-follower-initialize-from-backup.md
  3.9/administration-leader-follower-replication-applier.md
  3.9/administration-leader-follower-server-level-setup.md
  3.9/administration-leader-follower-setting-up.md
  3.9/administration-leader-follower-syncing-collections.md
  3.9/administration-leader-follower.md
  3.9/administration.md
  3.9/appendix-java-script-modules.md
  3.9/architecture-deployment-modes-active-failover-architecture.md
  3.9/architecture-deployment-modes-leader-follower-architecture.md
  3.9/architecture-deployment-modes-leader-follower-limitations.md
  3.9/architecture-deployment-modes-leader-follower.md
  3.9/architecture-deployment-modes.md
  3.9/architecture-replication.md
  3.9/data-modeling-databases-notes.md
  3.9/deployment-leader-follower-manual-start.md
  3.9/deployment-leader-follower.md
  3.9/deployment-manually.md
  3.9/deployment-modes.md
  3.9/deployment.md
  3.9/highlights.md
  3.9/index.md
  3.9/installation-linux.md
  3.9/installation-windows.md
  3.9/programs-arangodump-limitations.md
  3.9/programs-arangodump.md
  3.9/release-notes-new-features39.md
  3.9/scaling.md
  _data/3.10-manual.yml
  _data/3.9-manual.yml
Labels: cla-signed

#868 micro improvements
  3.9/release-notes-new-features39.md
  3.9/release-notes-upgrading-changes39.md
Labels: cla-signed

#870 Move shard id what's new to 3.9
  3.8/release-notes-new-features38.md
  3.9/release-notes-new-features39.md
Labels: cla-signed

#869 Add commas
  3.10/foxx-guides-browser.md
  3.4/foxx-guides-browser.md
  3.5/foxx-guides-browser.md
  3.6/foxx-guides-browser.md
  3.7/foxx-guides-browser.md
  3.8/foxx-guides-browser.md
  3.9/foxx-guides-browser.md
Labels: cla-signed

#866 extend the license grace period to 3 hours
  3.10/administration-license.md
  3.9/administration-license.md
  3.9/release-notes-new-features39.md
Labels: cla-signed

#872 clarify complexity limits
  3.10/aql/fundamentals-limitations.md
  3.9/aql/fundamentals-limitations.md
  3.9/release-notes-new-features39.md
  3.9/release-notes-upgrading-changes39.md
Labels: cla-signed

#873 Removed mention to internal shardIds
  drivers/spark-connector-new.md
Labels: cla-signed

#874 OAS-3817 | Oasis Disk Auto-Sizing Feature
  _data/oasis.yml
  oasis/deployments.md
  oasis/images/oasis-new-deployment2.png
  oasis/images/oasis-new-deployment3-developer.png
  oasis/images/oasis-new-deployment3-sharded.png
  oasis/oasisctl-completion.md
  oasis/oasisctl-create-deployment.md
  oasis/oasisctl-create-ipallowlist.md
  oasis/oasisctl-create-private-endpoint-service.md
  oasis/oasisctl-create-private-endpoint.md
  oasis/oasisctl-create-private.md
  oasis/oasisctl-create.md
  oasis/oasisctl-get-organization-authentication-providers.md
  oasis/oasisctl-get-organization-authentication.md
  oasis/oasisctl-get-organization-email-domain-restrictions.md
  oasis/oasisctl-get-organization-email-domain.md
  oasis/oasisctl-get-organization-email.md
  oasis/oasisctl-get-organization.md
  oasis/oasisctl-get-private-endpoint-service.md
  oasis/oasisctl-get-private-endpoint.md
  oasis/oasisctl-get-private.md
  oasis/oasisctl-get.md
  oasis/oasisctl-update-deployment.md
  oasis/oasisctl-update-ipallowlist.md
  oasis/oasisctl-update-organization-authentication-providers.md
  oasis/oasisctl-update-organization-authentication.md
  oasis/oasisctl-update-organization-email-domain-restrictions.md
  oasis/oasisctl-update-organization-email-domain.md
  oasis/oasisctl-update-organization-email.md
  oasis/oasisctl-update-organization.md
  oasis/oasisctl-update-private-endpoint-service.md
  oasis/oasisctl-update-private-endpoint.md
  oasis/oasisctl-update-private.md
  oasis/oasisctl-update.md
Labels: 1 Feature, cla-signed

#876 Fix small inaccuracies about threads
  3.10/programs-arangod-server.md
  3.7/programs-arangod-server.md
  3.8/programs-arangod-server.md
  3.9/programs-arangod-server.md
Labels: 9 Ready to Merge, cla-signed

#877 BTS-719 | Query explain output for 3.9 traversal optimizations
  3.9/release-notes-new-features39.md
Labels: 1 Feature, cla-signed

#875 BTS-745: Improve atomicity and isolation guarantee wording
  3.10/aql/operations-upsert.md
  3.10/data-modeling-operational-factors.md
  3.10/transactions-limitations.md
  3.10/transactions.md
  3.7/aql/operations-upsert.md
  3.7/data-modeling-operational-factors.md
  3.7/transactions-limitations.md
  3.7/transactions.md
  3.8/aql/operations-upsert.md
  3.8/data-modeling-operational-factors.md
  3.8/transactions-limitations.md
  3.8/transactions.md
  3.9/aql/operations-upsert.md
  3.9/data-modeling-operational-factors.md
  3.9/transactions-limitations.md
  3.9/transactions.md
Labels: 9 Ready to Merge, cla-signed

#884 OAS-4200: added locked resources info
  _data/oasis.yml
  oasis/access-control.md
  oasis/organizations.md
  oasis/projects.md
Labels: cla-signed

#882 Temporary fix for oasisctl completion Markdown rendering issues
  3.10/administration-active-failover.md
  oasis/oasisctl-completion.md
Labels: 9 Ready to Merge, 1 Bug, cla-signed

#887 add arangosync disjoint smart graph issue
  3.9/release-notes-known-issues39.md
Labels: cla-signed
