Repository arangodb/docs, pull requests merged in 2022-02, with the labels that each got.

#891 Update known issues 3.9
  3.7/release-notes-known-issues37.md
  3.8/release-notes-known-issues38.md
  3.9/release-notes-known-issues39.md
Labels: cla-signed

#892 Added info about deprecated npm modules
  3.10/appendix-java-script-modules.md
  3.9/appendix-deprecated.md
  3.9/appendix-java-script-modules.md
Labels: cla-signed

#893 Added a deprecation notice for hash and skiplist indexes
  3.9/appendix-deprecated.md
  3.9/http/indexes.md
Labels: cla-signed

#885 Add "Filtered" column to query profiling output
  3.10/aql/execution-and-performance-query-profiler.md
  3.10/release-notes-new-features310.md
Labels: cla-signed

#905 BTS-787 Update known issues for 3.9
  3.9/release-notes-known-issues39.md
Labels: cla-signed

#888 Change some default values for RocksDB memory usage
  3.10/programs-arangod-rocksdb.md
  3.10/release-notes-new-features310.md
  3.10/release-notes-upgrading-changes310.md
Labels: cla-signed

#900 Bugfix/spring data index annotations
  drivers/spring-data-reference-mapping-indexes.md
  drivers/spring-data-reference-mapping.md
  drivers/spring-data-reference-template-collection-manipulation.md
Labels: cla-signed

#907 clearify updates
  3.9/administration-license.md
Labels: cla-signed

#903 Document improved performance of nested loop joins for vpack index
  3.10/aql/execution-and-performance-query-statistics.md
  3.10/release-notes-api-changes310.md
Labels: cla-signed

#896 OAS-3818 | Oasis private network deployments (Azure Private Link)
  oasis/deployments.md
  oasis/images/oasis-deployment-private-network-menu.png
  oasis/images/oasis-deployment-private-network-setup2.png
  oasis/images/oasis-deployment-private-network.png
  oasis/images/oasis-deployments-page.png
Labels: 1 Feature, cla-signed

#901 [DE-45] Removed javadoc from Spring Data documentation
  _data/3.7-drivers.yml
  drivers/spring-data-getting-started.md
  drivers/spring-data-migration-migrating-1-x-3-0.md
  drivers/spring-data-migration-migrating-2-x-3-0.md
  drivers/spring-data-reference-mapping-auditing.md
  drivers/spring-data-reference-mapping-converter.md
  drivers/spring-data-reference-mapping-document.md
  drivers/spring-data-reference-mapping-edge.md
  drivers/spring-data-reference-mapping-events.md
  drivers/spring-data-reference-mapping-indexes.md
  drivers/spring-data-reference-mapping-reference.md
  drivers/spring-data-reference-mapping-relations.md
  drivers/spring-data-reference-mapping.md
  drivers/spring-data-reference-repositories-document-manipulation.md
  drivers/spring-data-reference-repositories-multi-document-manipulation.md
  drivers/spring-data-reference-repositories-queries-derived-queries.md
  drivers/spring-data-reference-repositories-queries-named-queries.md
  drivers/spring-data-reference-repositories-queries-query-methods.md
  drivers/spring-data-reference-repositories-queries.md
  drivers/spring-data-reference-repositories-query-by-example.md
  drivers/spring-data-reference-repositories.md
  drivers/spring-data-reference-template-collection-manipulation.md
  drivers/spring-data-reference-template-document-manipulation.md
  drivers/spring-data-reference-template-multi-document-manipulation.md
  drivers/spring-data-reference-template-queries.md
  drivers/spring-data-reference-template.md
  drivers/spring-data-reference.md
Labels: cla-signed

#909 Updated documentation of arangoimport
  3.10/programs-arangoimport-details.md
  3.10/programs-arangoimport-examples-json.md
  3.7/programs-arangoimport-details.md
  3.7/programs-arangoimport-examples-json.md
  3.8/programs-arangoimport-details.md
  3.8/programs-arangoimport-examples-json.md
  3.9/programs-arangoimport-details.md
  3.9/programs-arangoimport-examples-json.md
Labels: cla-signed

#899 Metrics API changes
  3.10/release-notes-api-changes310.md
Labels: cla-signed

#912 updates rdf link to interactive_tutorials repo
  3.10/data-modeling-graphs-from-rdf.md
  3.7/data-modeling-graphs-from-rdf.md
  3.8/data-modeling-graphs-from-rdf.md
  3.9/data-modeling-graphs-from-rdf.md
Labels: 9 Ready to Merge, cla-signed

#914 OAS-4415 | Improve guide about responding to org invites
  oasis/images/oasis-org-invite-email-verify.png
  oasis/images/oasis-org-invite-email.png
  oasis/images/oasis-org-invite-notification.png
  oasis/images/oasis-org-invite.png
  oasis/images/oasis-org-invites-accept.png
  oasis/my-account.md
Labels: 9 Ready to Merge, cla-signed

#890 BTS-697 | GeoJSON changes for 3.10
  3.10/aql/data-queries.md
  3.10/aql/functions-geo.md
  3.10/foxx-guides-webpack.md
  3.10/indexing-geo.md
  3.10/indexing-index-basics.md
  3.10/indexing-which-index.md
  3.10/release-notes-new-features310.md
  3.10/release-notes-upgrading-changes310.md
  3.7/aql/data-queries.md
  3.7/deployment-kubernetes-driver-configuration.md
  3.7/foxx-guides-webpack.md
  3.8/aql/data-queries.md
  3.8/foxx-guides-webpack.md
  3.9/aql/data-queries.md
  3.9/foxx-guides-webpack.md
Labels: 9 Ready to Merge, cla-signed

#911 BTS-386 | HTTP Error Handling and Response Codes
  3.10/http/general.md
  3.7/http/general.md
  3.8/http/general.md
  3.9/http/general.md
Labels: cla-signed

#919 BTS-459 | GeoJSON docs improvements
  3.10/analyzers.md
  3.10/indexing-geo.md
  3.10/indexing-index-basics.md
  3.10/indexing-which-index.md
  3.7/aql/functions-geo.md
  3.7/indexing-geo.md
  3.7/indexing-index-basics.md
  3.7/indexing-which-index.md
  3.8/analyzers.md
  3.8/aql/functions-geo.md
  3.8/indexing-geo.md
  3.8/indexing-index-basics.md
  3.8/indexing-which-index.md
  3.9/analyzers.md
  3.9/aql/functions-geo.md
  3.9/indexing-geo.md
  3.9/indexing-index-basics.md
  3.9/indexing-which-index.md
Labels: 9 Ready to Merge

#880 Misc changes to clean up old Github issues
  3.10/administration-configuration.md
  3.10/administration.md
  3.10/analyzers.md
  3.10/appendix-deprecated.md
  3.10/aql/examples-dynamic-attribute-names.md
  3.10/aql/functions-arangosearch.md
  3.10/aql/functions-numeric.md
  3.10/aql/operations-search.md
  3.10/arangosearch-fuzzy-search.md
  3.10/data-modeling-documents-document-methods.md
  3.10/graphs-general-graphs-management.md
  3.10/graphs-smart-graphs-management.md
  3.10/graphs.md
  3.10/http/indexes.md
  3.10/indexing-fulltext.md
  3.10/indexing-index-basics.md
  3.10/indexing-multi-dim.md
  3.10/programs-arangod-audit.md
  3.10/programs-arangod-cluster.md
  3.10/programs-arangodump-examples.md
  3.10/programs-arangodump-maskings.md
  3.10/programs-web-interface-cluster.md
  3.10/release-notes-new-features310.md
  3.7/administration-configuration.md
  3.7/aql/examples-dynamic-attribute-names.md
  3.7/aql/functions-arangosearch.md
  3.7/aql/operations-collect.md
  3.7/aql/operations-return.md
  3.7/aql/operations-search.md
  3.7/data-modeling-documents-document-methods.md
  3.7/graphs-general-graphs-management.md
  3.7/graphs.md
  3.7/programs-arangodump-maskings.md
  3.8/administration-configuration.md
  3.8/aql/examples-dynamic-attribute-names.md
  3.8/aql/functions-arangosearch.md
  3.8/aql/operations-search.md
  3.8/data-modeling-documents-document-methods.md
  3.8/graphs-general-graphs-management.md
  3.8/graphs.md
  3.8/programs-arangodump-maskings.md
  3.9/administration-configuration.md
  3.9/appendix-deprecated.md
  3.9/aql/examples-dynamic-attribute-names.md
  3.9/aql/functions-arangosearch.md
  3.9/aql/operations-search.md
  3.9/data-modeling-documents-document-methods.md
  3.9/graphs-general-graphs-management.md
  3.9/graphs.md
  3.9/programs-arangod-cluster.md
  3.9/programs-arangodump-maskings.md
  3.9/programs-web-interface-cluster.md
  3.9/release-notes-new-features39.md
  3.9/release-notes-upgrading-changes39.md
  README.md
  drivers/index.md
Labels: 9 Ready to Merge, cla-signed
