Repository arangodb/docs, pull requests merged in 2022-11, with the labels that each got.

#1160 Spelling: vertex centric -> vertex-centric
  3.8/indexing-index-basics.md
  3.8/indexing-vertex-centric.md
  3.9/indexing-vertex-centric.md
  _data/3.8-manual.yml
  _data/3.9-manual.yml
Labels: cla-signed

#1159 Make sure there is only one level 1 headline in the content
  3.10/smart-and-satellite-graphs-single-server.md
  3.11/smart-and-satellite-graphs-single-server.md
  drivers/php-tutorial.md
  drivers/php.md
Labels: cla-signed

#1161 Remove scripts from Gitbook to Jekyll migration
  .gitignore
  .htmltest-external.yml
  TODO.md
  _config.yml
  _layouts/relative-redirect.html
  assets/aql_query_with_traversal.png
  assets/arangodb_logo_2016_inverted.png
  migrate.sh
  scripts/changeLink.js
  scripts/fetchRefs.sh
  scripts/migrate.js
  scripts/nav2json.js
  scripts/package.json
  scripts/yarn.lock
Labels: cla-signed

#1168 Correct/unify spelling of "indexes"
  3.10/aql/examples-combining-graph-traversals.md
  3.10/aql/examples-join.md
  3.10/aql/extending.md
  3.10/aql/functions-date.md
  3.10/aql/operations-for.md
  3.10/aql/operations-upsert.md
  3.10/downgrading.md
  3.10/highlights.md
  3.10/indexing-vertex-centric.md
  3.10/installation-linux-osconfiguration.md
  3.10/programs-web-interface-collections.md
  3.10/release-notes-new-features35.md
  3.10/release-notes-upgrading-changes35.md
  3.11/aql/examples-combining-graph-traversals.md
  3.11/aql/examples-join.md
  3.11/aql/extending.md
  3.11/aql/functions-date.md
  3.11/aql/operations-for.md
  3.11/aql/operations-upsert.md
  3.11/downgrading.md
  3.11/highlights.md
  3.11/indexing-vertex-centric.md
  3.11/installation-linux-osconfiguration.md
  3.11/programs-web-interface-collections.md
  3.11/release-notes-new-features35.md
  3.11/release-notes-upgrading-changes35.md
  3.8/aql/examples-combining-graph-traversals.md
  3.8/aql/examples-join.md
  3.8/aql/extending.md
  3.8/aql/functions-date.md
  3.8/aql/operations-for.md
  3.8/aql/tutorial-join.md
  3.8/downgrading.md
  3.8/highlights.md
  3.8/indexing-vertex-centric.md
  3.8/installation-linux-osconfiguration.md
  3.8/programs-web-interface-collections.md
  3.8/release-notes-new-features35.md
  3.8/release-notes-upgrading-changes35.md
  3.9/aql/examples-combining-graph-traversals.md
  3.9/aql/examples-join.md
  3.9/aql/extending.md
  3.9/aql/functions-date.md
  3.9/aql/operations-for.md
  3.9/aql/operations-upsert.md
  3.9/aql/tutorial-join.md
  3.9/downgrading.md
  3.9/highlights.md
  3.9/indexing-vertex-centric.md
  3.9/installation-linux-osconfiguration.md
  3.9/programs-web-interface-collections.md
  3.9/release-notes-new-features35.md
  3.9/release-notes-upgrading-changes35.md
Labels: 9 Ready to Merge, cla-signed

#1171 deprecate `--agency.pool-size` startup option
  3.11/programs-arangod-agency.md
  3.11/release-notes-upgrading-changes311.md
Labels: cla-signed

#1172 DOC-51 | Limit never applies to write operations
  3.10/aql/operations-limit.md
  3.11/aql/operations-limit.md
  3.7/aql/operations-limit.md
  3.8/aql/operations-limit.md
  3.9/aql/operations-limit.md
Labels: cla-signed

#1140 Added startup option --query.log-failed-queries to optionally log all…
  3.10/programs-arangod-query.md
  3.10/release-notes-new-features310.md
  3.11/programs-arangod-query.md
  3.9/programs-arangod-query.md
  3.9/release-notes-new-features39.md
Labels: cla-signed

#1143 Update deps 2022-10-11
  .htmltest.yml
  3.10/deployment-kubernetes-usage.md
  3.10/start-using-aql.md
  3.10/transactions-stream-transactions.md
  3.11/deployment-kubernetes-usage.md
  3.11/start-using-aql.md
  3.11/transactions-stream-transactions.md
  3.6/deployment-kubernetes-usage.md
  3.7/deployment-kubernetes-usage.md
  3.8/deployment-kubernetes-usage.md
  3.8/transactions-stream-transactions.md
  3.9/deployment-kubernetes-usage.md
  3.9/transactions-stream-transactions.md
  Dockerfile
  Gemfile.lock
  README.md
  _config.yml
  _plugins/versions/generator.rb
  build.sh
  netlify.sh
  netlify.toml
  sitemap.rb
Labels: 9 Ready to Merge, cla-signed

#1186 Warning Installation Windows
  3.10/installation-windows.md
  3.11/installation-windows.md
  3.8/installation-windows.md
  3.9/installation-windows.md
Labels: cla-signed

#1178 DOC-205 | kube-arangodb: Use arm64 architecture for deployment
  3.10/deployment-kubernetes-deployment-resource.md
  3.10/deployment-kubernetes-usage.md
  3.11/deployment-kubernetes-deployment-resource.md
  3.11/deployment-kubernetes-usage.md
  3.8/deployment-kubernetes-deployment-resource.md
  3.8/deployment-kubernetes-usage.md
  3.9/deployment-kubernetes-deployment-resource.md
  3.9/deployment-kubernetes-usage.md
Labels: cla-signed

#1179 DOC-80 | Nested FOR loops (joins) over DOCUMENT(), part 2
  3.10/aql/fundamentals-limitations.md
  3.10/aql/fundamentals-subqueries.md
  3.10/aql/operations-for.md
  3.10/aql/operations-return.md
  3.10/aql/operators.md
  3.11/aql/fundamentals-limitations.md
  3.11/aql/fundamentals-subqueries.md
  3.11/aql/operations-for.md
  3.11/aql/operations-return.md
  3.11/aql/operators.md
  3.11/data-modeling-databases.md
  3.11/quick-start-guide.md
  _data/3.10-aql.yml
  _data/3.11-aql.yml
Labels: cla-signed

#1180 DOC-227 | Move guide about reducing memory footprint to administration section
  3.10/administration-reduce-memory-footprint.md
  3.10/tutorials.md
  3.11/administration-reduce-memory-footprint.md
  3.11/tutorials.md
  _data/3.10-manual.yml
  _data/3.11-manual.yml
Labels: cla-signed

#1183 Field normalization cache can also be enabled per field
  3.9/arangosearch-performance.md
  3.9/release-notes-new-features39.md
Labels: 9 Ready to Merge, cla-signed

#1181 DOC-215 | Clarify difference between UPDATE/REPLACE syntaxes
  3.10/aql/operations-replace.md
  3.10/aql/operations-update.md
  3.11/aql/operations-replace.md
  3.11/aql/operations-update.md
  _data/3.10-aql.yml
  _data/3.11-aql.yml
Labels: cla-signed

#1189 Follow up DOC-215 / Updated lead paragraph
  3.10/appendix-glossary.md
  3.10/aql/functions-document.md
  3.10/aql/operations-replace.md
  3.10/programs-arangoimport-details.md
  3.11/appendix-glossary.md
  3.11/aql/functions-document.md
  3.11/aql/operations-replace.md
  3.11/programs-arangoimport-details.md
  3.8/appendix-glossary.md
  3.8/aql/functions-document.md
  3.8/aql/operations-replace.md
  3.8/aql/operations-update.md
  3.8/programs-arangoimport-details.md
  3.9/appendix-glossary.md
  3.9/aql/functions-document.md
  3.9/aql/operations-replace.md
  3.9/aql/operations-update.md
  3.9/programs-arangoimport-details.md
Labels: 9 Ongoing Discussion, cla-signed

#1190 Partially revert #1175 because `primarySortCache` will be released in v3.9.6
  3.10/arangosearch-views-search-alias.md
  3.10/arangosearch-views.md
  3.11/arangosearch-views-search-alias.md
  3.11/arangosearch-views.md
  3.9/arangosearch-performance.md
  3.9/arangosearch-views.md
  3.9/release-notes-api-changes39.md
  3.9/release-notes-new-features39.md
Labels: cla-signed

#1176 ArangoGraph Notebooks update
  arangograph/images/arangograph-notebooks-architecture.png
  arangograph/images/arangograph-notebooks.png
  arangograph/notebooks.md
Labels: cla-signed

#1192 DOC 192 / ArangoGraph multi-region backups
  arangograph/backups.md
  arangograph/images/arangograph-back-up-now-dialog.png
  arangograph/images/arangograph-back-up-now.png
  arangograph/images/arangograph-backup-policy-schedule.png
  arangograph/images/arangograph-backup-section.png
  arangograph/images/arangograph-clone-deployment-from-backup.png
  arangograph/images/arangograph-clone-select-region.png
  arangograph/images/arangograph-copy-backup-different-region.png
  arangograph/images/arangograph-edit-backup-policy.png
  arangograph/images/arangograph-multi-region-backup.png
  arangograph/images/arangograph-multiple-backups.png
  arangograph/images/arangograph-restore-from-backup-dialog.png
  arangograph/images/arangograph-restore-from-backup.png
Labels: cla-signed

#1187 DOC-205 | kube-arangodb: Correct spec.architecture description
  3.10/deployment-kubernetes-deployment-resource.md
  3.10/deployment-kubernetes-usage.md
  3.11/deployment-kubernetes-deployment-resource.md
  3.11/deployment-kubernetes-usage.md
  3.8/deployment-kubernetes-deployment-resource.md
  3.8/deployment-kubernetes-usage.md
  3.9/deployment-kubernetes-deployment-resource.md
  3.9/deployment-kubernetes-usage.md
Labels: cla-signed

#1173 obsolete startup option `--database.force-sync-properties`
  3.11/release-notes-upgrading-changes311.md
Labels: cla-signed

#1170 DOC-235 | Add unary NOT and AT LEAST to operator precedence table
  3.10/aql/operators.md
  3.11/aql/operators.md
  3.8/aql/operators.md
  3.9/aql/operators.md
Labels: cla-signed

#1194 Fix typo in AQL Analyzer option "collapsePositions"
  3.10/analyzers.md
  3.11/analyzers.md
  3.8/analyzers.md
  3.9/analyzers.md
Labels: cla-signed

#1198 Migration agent - adjust step about switching endpoint
  arangograph/cloud-migration-tool.md
Labels: cla-signed

#1197 DOC-236 / update arangograph limitations
  3.10/quick-start-in-the-cloud.md
  3.11/quick-start-in-the-cloud.md
Labels: cla-signed
