Repository arangodb/docs, pull requests merged in 2023-03, with the labels that each got.

#1291 added documentation for BTS-1249
  3.10/security-security-options.md
  3.11/security-security-options.md
Labels: cla-signed

#1292 BTS-1252 | arangorestore cannot preserve _rev value
  3.10/programs-arangorestore-examples.md
  3.11/programs-arangorestore-examples.md
  3.8/programs-arangorestore-examples.md
  3.9/programs-arangorestore-examples.md
Labels: cla-signed

#1295 update documentation for "hashed" COLLECT variant
  3.11/aql/operations-collect.md
  3.11/release-notes-new-features311.md
Labels: 9 Ready to Merge, cla-signed

#1294 DOC-339 | Install with Docker instructions
  3.10/features-community-edition.md
  3.10/install-with-docker.md
  3.10/installation.md
  3.11/features-community-edition.md
  3.11/install-with-docker.md
  3.11/installation.md
  _data/3.10-manual.yml
  _data/3.11-manual.yml
Labels: cla-signed

#1296 DOC-422 | Release note updates for 3.9 and 3.10
  3.10/programs-arangod-env-vars.md
  3.10/release-notes-api-changes310.md
  3.10/release-notes-new-features310.md
  3.10/release-notes-upgrading-changes310.md
  3.10/security-security-options.md
  3.11/programs-arangod-env-vars.md
  3.11/release-notes-new-features311.md
  3.11/security-security-options.md
  3.7/programs-arangod-options.md
  3.8/programs-arangod-options.md
  3.8/release-notes-api-changes38.md
  3.8/release-notes-new-features38.md
  3.8/release-notes-upgrading-changes38.md
  3.9/programs-arangod-env-vars.md
  3.9/programs-arangod-options.md
  3.9/programs-arangod-rocksdb.md
  3.9/release-notes-api-changes39.md
  3.9/release-notes-new-features39.md
  3.9/release-notes-upgrading-changes39.md
Labels: cla-signed

#1297 DOC-389 | Improve Certificates in ArangoGraph
  3.10/quick-start-in-the-cloud.md
  3.11/quick-start-in-the-cloud.md
  _data/arangograph.yml
  arangograph/certificates.md
  arangograph/deployments.md
  arangograph/images/arangograph-cert-install-instructions.png
  arangograph/images/arangograph-cert-page-with-cert-present.png
  arangograph/images/arangograph-connecting-drivers.png
  arangograph/images/arangograph-new-certificate.png
  arangograph/overview.md
  arangograph/projects.md
Labels: cla-signed

#1302 ArangoGraph | Upgrades and versioning
  _data/arangograph.yml
  arangograph/certificates.md
  arangograph/deployments.md
  arangograph/images/arangograph-version-security.png
  arangograph/private-endpoints.md
  arangograph/upgrades-versioning.md
Labels: cla-signed

#1305 Versioning ArangoGraph | Minor follow-up fixes
  arangograph/images/arangograph-version-security.png
  arangograph/upgrades-versioning.md
Labels: cla-signed

#1306 Remove/replace links to pages that get redirected
  3.10/appendix-deprecated.md
  3.10/quick-start-guide.md
  3.10/release-notes-upgrading-changes310.md
  3.11/appendix-deprecated.md
  3.11/quick-start-guide.md
Labels: cla-signed

#1307 DOC-433 | Adjust description of AQL `APPEND()` to actual behavior
  3.10/aql/functions-array.md
  3.11/aql/functions-array.md
  3.7/aql/functions-array.md
  3.8/aql/functions-array.md
  3.9/aql/functions-array.md
Labels: cla-signed

#1312 Remove some question marks from headlines
  3.10/architecture.md
  3.10/deployment-oneshard.md
  3.10/graphs-enterprise-graphs.md
  3.10/graphs-smart-graphs.md
  3.10/graphs.md
  3.11/architecture.md
  3.11/deployment-oneshard.md
  3.11/graphs-enterprise-graphs.md
  3.11/graphs-smart-graphs.md
  3.11/graphs.md
Labels: cla-signed

#1313 Ensure "On this page" is above example boxes and remove unused, empty CSS file
  styles/page-toc.css
  styles/site.css
Labels: 1 Bug, cla-signed

#1304 Directly include the content of the documentRevision DocuBlock
  3.10/appendix-glossary.md
  3.10/data-modeling-documents-document-address.md
  3.10/http/document-address-and-etag.md
  3.11/appendix-glossary.md
  3.11/data-modeling-documents-document-address.md
  3.11/http/document-address-and-etag.md
Labels: cla-signed

#1301 Deprecation/Removal notice of two Pregel features for 3.11
  3.11/appendix-deprecated.md
  3.11/graph-analytics-custom-pregel.md
  3.11/release-notes-upgrading-changes311.md
Labels: cla-signed

#1314 [GORDO-1590] Remove mention of memory-mapped datasets for Pregel
  3.11/appendix-deprecated.md
  3.11/graphs-pregel.md
  3.11/release-notes-upgrading-changes311.md
Labels: cla-signed

#1315 Limitations of Spark speculative execution
  drivers/spark-connector-new.md
Labels: cla-signed
