Repository arangodb/docs, pull requests merged in 2023-05, with the labels that each got.

#1347 Upgraded bundled library versions for 3.11
  3.11/release-notes-new-features311.md
Labels: cla-signed

#1348 clarify that unicodes names must be NFC-normalized
  3.11/release-notes-api-changes311.md
  3.11/release-notes-new-features311.md
  3.11/release-notes-upgrading-changes311.md
Labels: cla-signed

#1349 mention downwards-incompatible change
  3.11/release-notes-api-changes311.md
  3.11/release-notes-upgrading-changes311.md
Labels: cla-signed

#1352 Add deprecation notice to AQL fulltext functions
  3.10/aql/functions-fulltext.md
  3.11/aql/functions-fulltext.md
Labels: cla-signed

#1355 DOC-464 | Add metrics for delays in sending cluster-internal requests
  3.10/release-notes-api-changes310.md
  3.10/release-notes-new-features310.md
  3.11/release-notes-api-changes311.md
  3.11/release-notes-new-features311.md
  3.9/release-notes-api-changes39.md
  3.9/release-notes-new-features39.md
Labels: cla-signed

#1359 Suggesting changes for better readability and clarity
  3.10/administration-cluster.md
  3.11/administration-cluster.md
  3.12/administration-cluster.md
  3.9/administration-cluster.md
Labels: cla-signed

#1356 BM25() text length scaling 0..1
  3.10/aql/functions-arangosearch.md
  3.11/aql/functions-arangosearch.md
  3.12/aql/functions-arangosearch.md
  3.9/aql/functions-arangosearch.md
Labels: cla-signed

#1316 DOC-385 | Add overview of Tools to Getting Started
  3.10/how-to-interact-with-arangodb.md
  3.10/quick-start-guide.md
  3.11/how-to-interact-with-arangodb.md
  3.11/quick-start-guide.md
  3.12/how-to-interact-with-arangodb.md
  3.12/quick-start-guide.md
Labels: cla-signed

#1341 DOC-395 | Recommend to take a backup before upgrading
  3.10/deployment-kubernetes-upgrading.md
  3.10/downgrading.md
  3.10/upgrading-community-to-enterprise.md
  3.10/upgrading-manually-active-failover.md
  3.10/upgrading-manually-cluster.md
  3.10/upgrading-osspecific-info-linux.md
  3.10/upgrading-osspecific-info-mac-os.md
  3.10/upgrading-osspecific-info-windows.md
  3.10/upgrading-starter.md
  3.10/upgrading.md
  3.11/deployment-kubernetes-upgrading.md
  3.11/downgrading.md
  3.11/upgrading-community-to-enterprise.md
  3.11/upgrading-manually-active-failover.md
  3.11/upgrading-manually-cluster.md
  3.11/upgrading-osspecific-info-linux.md
  3.11/upgrading-osspecific-info-mac-os.md
  3.11/upgrading-osspecific-info-windows.md
  3.11/upgrading-starter.md
  3.11/upgrading.md
  3.12/deployment-kubernetes-upgrading.md
  3.12/downgrading.md
  3.12/upgrading-community-to-enterprise.md
  3.12/upgrading-manually-active-failover.md
  3.12/upgrading-manually-cluster.md
  3.12/upgrading-osspecific-info-linux.md
  3.12/upgrading-osspecific-info-mac-os.md
  3.12/upgrading-osspecific-info-windows.md
  3.12/upgrading-starter.md
  3.12/upgrading.md
Labels: cla-signed

#1361 DOC-468 | BTS-1341 | ArangoSearch Views building in progress query warning
  3.11/arangosearch.md
  3.11/release-notes-api-changes311.md
  3.12/arangosearch.md
Labels: cla-signed

#1365 Add link to kube repo and fix some typos
  3.10/aql/execution-and-performance-optimizer.md
  3.10/deployment-kubernetes.md
  3.11/aql/execution-and-performance-optimizer.md
  3.11/deployment-kubernetes.md
  3.12/aql/execution-and-performance-optimizer.md
  3.12/deployment-kubernetes.md
Labels: cla-signed

#1368 From 3.9 on, Hot Backups include View data (not only View definitions)
  3.10/http/hot-backup.md
  3.11/http/hot-backup.md
  3.12/http/hot-backup.md
  3.9/http/hot-backup.md
Labels: cla-signed

#1366 Update changelog for 12th May 2023
  arangograph/changelog.md
Labels: cla-signed

#1369 DOC-380 | New graph viewer
  3.11/images/graphViewer.png
  3.11/images/graphViewerContextMenu.png
  3.11/programs-web-interface-graphs.md
  3.11/release-notes-new-features311.md
  3.12/images/graphViewer.png
  3.12/images/graphViewerContextMenu.png
  3.12/programs-web-interface-graphs.md
Labels: cla-signed

#1373 DOC-406 | Release notes: k_shortest_paths performance improvements
  3.11/release-notes-new-features311.md
Labels: cla-signed

#1364 Update cloud-migration-tool for release
  arangograph/cloud-migration-tool.md
Labels: cla-signed

#1362 Add metrics `arangodb_file_descriptors_limit` and `rocksdb_cache_peak_allocated`
  3.10/release-notes-api-changes310.md
  3.10/release-notes-new-features310.md
  3.11/release-notes-api-changes311.md
  3.11/release-notes-new-features311.md
  3.9/release-notes-new-features39.md
Labels: 9 Waiting for Upstream Merge, cla-signed

#1357 DOC-372 | Release notes for Telemetrics
  3.11/appendix-telemetrics.md
  3.11/appendix.md
  3.11/release-notes-new-features311.md
  3.12/appendix-telemetrics.md
  3.12/appendix.md
  _data/3.11-manual.yml
  _data/3.12-manual.yml
Labels: cla-signed

#1326 DOC-420 | High level restructuring
  3.10/aql/examples.md
  3.10/aql/operations-insert.md
  3.10/data-modeling-monetary-data-without-precision-loss.md
  3.10/data-models.md
  3.10/data-science-adapters.md
  3.10/data-structure.md
  3.10/features-community-edition.md
  3.10/graphs-traversals-example-data.md
  3.10/indexing-index-basics.md
  3.10/programs-arangorestore-examples.md
  3.10/programs-web-interface-graphs.md
  3.10/quick-start-guide.md
  3.11/aql/examples.md
  3.11/aql/operations-insert.md
  3.11/data-modeling-monetary-data-without-precision-loss.md
  3.11/data-models.md
  3.11/data-science-adapters.md
  3.11/data-structure.md
  3.11/features-community-edition.md
  3.11/graphs-traversals-example-data.md
  3.11/indexing-index-basics.md
  3.11/programs-arangorestore-examples.md
  3.11/quick-start-guide.md
  3.12/aql/examples.md
  3.12/aql/operations-insert.md
  3.12/data-modeling-monetary-data-without-precision-loss.md
  3.12/data-models.md
  3.12/data-science-adapters.md
  3.12/data-structure.md
  3.12/features-community-edition.md
  3.12/graphs-traversals-example-data.md
  3.12/indexing-index-basics.md
  3.12/programs-arangorestore-examples.md
  3.12/quick-start-guide.md
  _data/3.10-manual.yml
  _data/3.11-manual.yml
  _data/3.12-manual.yml
Labels: cla-signed

#1367 Improve shard rebalancing documentation
  3.10/http/cluster.md
  3.11/http/cluster.md
  3.12/http/cluster.md
Labels: cla-signed

#1377 DOC-476 | Resolve issue with files not linked to navigation definition
  3.10/backup-restore.md
  3.10/programs-arangobackup-limitations.md
  3.11/backup-restore.md
  3.11/programs-arangobackup-limitations.md
  3.12/backup-restore.md
  3.12/programs-arangobackup-limitations.md
  3.8/backup-restore.md
  3.8/programs-arangobackup-limitations.md
  3.9/backup-restore.md
  3.9/programs-arangobackup-limitations.md
  arangograph/getting-started.md
  arangograph/index.md
  arangograph/overview.md
Labels: 1 Bug, cla-signed

#1380 Known issues for 3.11
  3.11/release-notes-known-issues311.md
Labels: cla-signed

#1383 Added documentation for sequences of SORT
  3.10/aql/operations-sort.md
  3.11/aql/operations-sort.md
  3.12/aql/operations-sort.md
  3.9/aql/operations-sort.md
Labels: cla-signed

#1376 Added `--query.max-collections-per-query` option
  3.10/aql/fundamentals-limitations.md
  3.10/release-notes-new-features310.md
  3.11/aql/fundamentals-limitations.md
  3.11/release-notes-new-features311.md
  3.12/aql/fundamentals-limitations.md
Labels: cla-signed

#1389 Feature/max collections per query
  3.10/aql/fundamentals-limitations.md
  3.10/release-notes-new-features310.md
  3.11/aql/fundamentals-limitations.md
  3.11/release-notes-new-features311.md
  3.12/aql/fundamentals-limitations.md
Labels: cla-signed

#1388 fix typo
  3.11/release-notes-upgrading-changes311.md
Labels: cla-signed

#1382 remove JavaScript-based traversals
  3.12/appendix-deprecated.md
  3.12/release-notes-api-changes312.md
  3.12/release-notes-upgrading-changes312.md
Labels: cla-signed

#1374 Remove mention of `--ignore-distribute-shards-like-errors` startup option
  3.10/programs-arangodump-examples.md
  3.10/programs-arangorestore-examples.md
  3.11/programs-arangodump-examples.md
  3.11/programs-arangorestore-examples.md
  3.12/programs-arangodump-examples.md
  3.12/programs-arangorestore-examples.md
Labels: cla-signed
