Repository arangodb/docs, pull requests merged in 2023-04, with the labels that each got.

#1319 Edge collections of SmartGraphs and EnterpriseGraphs now report actual `numberOfShards`
  3.11/release-notes-api-changes311.md
Labels: cla-signed

#1322 DOC-442 | Authentication of notebooks
  arangograph/access-control.md
  arangograph/images/arangograph-notebooks.png
  arangograph/notebooks.md
Labels: cla-signed

#1320 DOC-394 | peakMemoryUsage for running and slow queries
  3.11/release-notes-api-changes311.md
  3.11/release-notes-new-features311.md
Labels: cla-signed

#1308 DOC-434 | [APM-283] Add release notes and update documentation for parallel gather
  3.11/aql/execution-and-performance-optimizer.md
  3.11/release-notes-new-features311.md
  3.11/release-notes-upgrading-changes311.md
Labels: 1 Feature, cla-signed

#1324 GEO_DISTANCE() uses meters as unit
  3.10/aql/functions-geo.md
  3.11/aql/functions-geo.md
  3.9/aql/functions-geo.md
Labels: cla-signed

#1318 GT-390 Update ArangoLocalStorage doc
  3.10/deployment-kubernetes-storage-resource.md
  3.10/deployment-kubernetes-storage.md
  3.11/deployment-kubernetes-storage-resource.md
  3.11/deployment-kubernetes-storage.md
  3.9/deployment-active-failover-manual-start.md
  3.9/deployment-active-failover-using-the-starter.md
  3.9/deployment-cluster-manual-start.md
  3.9/deployment-kubernetes-backup-policy-resource.md
  3.9/deployment-kubernetes-backup-resource.md
  3.9/deployment-kubernetes-config-and-secrets.md
  3.9/deployment-kubernetes-deployment-replication-resource.md
  3.9/deployment-kubernetes-deployment-resource.md
  3.9/deployment-kubernetes-driver-configuration.md
  3.9/deployment-kubernetes-storage-resource.md
  3.9/deployment-kubernetes-storage.md
  3.9/deployment-kubernetes-troubleshooting.md
  3.9/deployment-kubernetes-usage.md
  3.9/deployment-single-instance-manual-start.md
  3.9/deployment-single-instance-using-the-starter.md
  3.9/deployment-standalone-agency.md
  3.9/tutorials-kubernetes-dc2-dc.md
  3.9/tutorials-kubernetes.md
Labels: cla-signed

#1303 DOC-200 | Notebooks: Update magic commands
  arangograph/notebooks.md
Labels: cla-signed

#1321 DOC-363 | New Web UI for ArangoSearch Views
  3.11/arangosearch-views-search-alias.md
  3.11/arangosearch-views.md
  3.11/images/arangosearch-create-new-view.png
  3.11/images/arangosearch-create-search-alias-view.png
  3.11/release-notes-new-features311.md
Labels: cla-signed

#1325 Update indexing-inverted.md
  3.10/indexing-inverted.md
  3.11/indexing-inverted.md
Labels: 9 CLA available

#1323 DOC-391 | Release notes for AQL graph traversal tracing
  3.11/release-notes-api-changes311.md
  3.11/release-notes-new-features311.md
Labels: cla-signed

#1328 DOC-458 | MDS-1001 | Optimize access to last element in traversal
  3.10/aql/execution-and-performance-optimizer.md
  3.11/aql/execution-and-performance-optimizer.md
  3.11/release-notes-new-features311.md
  3.9/aql/execution-and-performance-optimizer.md
Labels: cla-signed

#1330 DOC-361 | Release notes for Custom Queries UI, new sort mechanism and search box
  3.11/release-notes-new-features311.md
Labels: cla-signed

#1332 DOC-362 | Release notes for inverted indexes UI
  3.11/release-notes-new-features311.md
Labels: cla-signed

#1338 Move start of `{% comment %}` block to adjacent line in table for Hugo toolchain
  3.10/aql/fundamentals-syntax.md
  3.10/data-model-and-concepts.md
  3.10/features.md
  3.11/aql/fundamentals-syntax.md
  3.11/data-model-and-concepts.md
  3.11/features.md
Labels: cla-signed

#1327 DOC-354 | APM-407 | AQL bulk INSERT operations
  3.11/aql/examples-upsert-repsert.md
  3.11/aql/execution-and-performance-optimizer.md
  3.11/release-notes-new-features311.md
Labels: cla-signed

#1329 DOC-355 | Extended names for collections, Views, and indexes
  3.10/analyzers.md
  3.10/aql/fundamentals-data-types.md
  3.10/aql/fundamentals-syntax.md
  3.10/data-model-and-concepts.md
  3.10/data-modeling-databases.md
  3.10/programs-arangodump-maskings.md
  3.11/analyzers.md
  3.11/aql/fundamentals-data-types.md
  3.11/aql/fundamentals-syntax.md
  3.11/data-model-and-concepts.md
  3.11/data-modeling-collections.md
  3.11/data-modeling-databases.md
  3.11/data-modeling-documents.md
  3.11/data-modeling-views.md
  3.11/indexing-working-with-indexes.md
  3.11/programs-arangodump-maskings.md
  3.11/release-notes-api-changes311.md
  3.11/release-notes-new-features311.md
  3.11/release-notes-upgrading-changes311.md
  3.9/data-modeling-naming-conventions-database-names.md
  3.9/release-notes-api-changes39.md
  drivers/spring-data-reference-repositories-queries.md
Labels: cla-signed

#1342 [DE-570] Java driver v7
  _data/drivers.yml
  drivers/index.md
  drivers/java-changes-v7.md
  drivers/java-reference-serialization.md
  drivers/java-reference-setup.md
  drivers/java-reference.md
  drivers/java-v6-reference-serialization.md
  drivers/java-v6-reference-setup.md
  drivers/java-v6.md
  drivers/java.md
  drivers/spark-connector-new.md
Labels: cla-signed

#1345 add requirement for system page size to documentation
  3.10/installation-linux-osconfiguration.md
  3.10/installation.md
  3.11/installation-linux-osconfiguration.md
  3.11/installation.md
  3.9/installation-linux-osconfiguration.md
Labels: cla-signed

#1343 added more infos to release notes
  3.10/release-notes-api-changes310.md
  3.10/release-notes-new-features310.md
  3.11/features-community-edition.md
  3.11/highlights.md
  3.11/release-notes-api-changes311.md
  3.11/release-notes-new-features311.md
  3.9/release-notes-new-features39.md
Labels: cla-signed

#1339 Release notes for `--server.ensure-whitespace-metrics-format`
  3.10/release-notes-api-changes310.md
  3.10/release-notes-new-features310.md
  3.11/release-notes-api-changes311.md
  3.11/release-notes-new-features311.md
Labels: cla-signed

#1331 Documentation for BlobDB parameters
  3.11/release-notes-new-features311.md
Labels: cla-signed

#1346 DOC-405 | Mark version 3.8 as deprecated
  _data/deprecations.yml
Labels: cla-signed
